name: Pruebas automatizadas Github Actions

on:
  push:
    branches:
      - prueba_tes_automatizados
  pull_request:
    branches:
      - prueba_tes_automatizados

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python 3.12.7 on Windows
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Run tests
    - name: Run tests
      run: pytest

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy
      run: |
        echo "Deployment step (customize as needed)"
